package com.gotop.dict.dao.impl;

import com.gotop.dict.dao.IEosDictEntryDAO;
import com.gotop.dict.model.EosDictEntry;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;
import java.util.List;
import java.util.Map;

import org.apache.log4j.Logger;

public class EosDictEntryDAO extends SqlMapClientDao implements IEosDictEntryDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(EosDictEntryDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table EOS_DICT_ENTRY
     *
     * @abatorgenerated 
     */
    public EosDictEntryDAO() {
        super();
    }

    /**
     * 插入一条新数据.
     */
    public void insert(EosDictEntry record) {
        getSqlMapClientTemplate().insert("EOS_DICT_ENTRY_SqlMap.abatorgenerated_insert", record);
    }

    /**
     * 通过主键更新一条全部字段内容
     */
    public int updateByPrimaryKey(EosDictEntry record) {
        int rows = getSqlMapClientTemplate().update("EOS_DICT_ENTRY_SqlMap.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

	@Override
	public List dictTypeList(Map<String, Object> map, Page page) {
		List list = queryForList("EOS_DICT_ENTRY_SqlMap.dictTypeList", map, page);
	      return list;
	}
}