package com.gotop.Generalprocess.dao.impl;

import com.gotop.Generalprocess.dao.ITGeneralprocessModelfourDAO;
import com.gotop.Generalprocess.model.ProcessModelFour;
import com.gotop.Generalprocess.model.ProcessModelThree;
import com.gotop.Generalprocess.model.TGeneralprocessModelfour;
import com.gotop.Generalprocess.model.TGeneralprocessModelfourExample;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;
import java.util.HashMap;
import java.util.List;
import org.apache.log4j.Logger;

public class TGeneralprocessModelfourDAO extends SqlMapClientDao implements ITGeneralprocessModelfourDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TGeneralprocessModelfourDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table T_GENERALPROCESS_MODELFOUR
     *
     * @abatorgenerated 
     */
    public TGeneralprocessModelfourDAO() {
        super();
    }

    /**
     * 插入一条新数据.
     * @abatorgenerated
     */
    public void insert(TGeneralprocessModelfour record) {
        getSqlMapClientTemplate().insert("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_insert", record);
    }

    /**
     * 通过查询实例，查询记录
     * @abatorgenerated
     */
    public List selectByExample(TGeneralprocessModelfourExample example) {
        List list = queryForList("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * 通过Map方式的动态条件，查询分页数据
     * @abatorgenerated
     */
    public List selectByMapAndPage(HashMap example) {
        List list = queryForList("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_selectByMapAndPage", example);
        return list;
    }

    /**
     * 通过Bean方式的动态条件，查询分页数据
     * @abatorgenerated
     */
    public List selectByExampleAndPage(TGeneralprocessModelfour record, TGeneralprocessModelfourExample example, Page page) {
         UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
         List list = queryForList("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_selectByExampleAndPage",parms,page);
        return list;
    }

    /**
     * 根据查询模板的查询结果扩展一个实例
     * @abatorgenerated
     * @param example 条件
     */
    public TGeneralprocessModelfour expandEntityByTemplate(TGeneralprocessModelfour example) {
        TGeneralprocessModelfour result = (TGeneralprocessModelfour)queryForObject("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_expandEntityByTemplate", example);
        return result;
    }

    /**
     * 根据Bean数据模板查询条件查询所有记录
     * @abatorgenerated
     * @param example 条件
     */
    public List queryEntitiesByTemplate(TGeneralprocessModelfour example) {
        List<TGeneralprocessModelfour> result = (List<TGeneralprocessModelfour>)queryForList("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_queryEntitiesByTemplate", example);
        return result;
    }

    /**
     * 根据Bean数据模板分页查询
     * @abatorgenerated
     * @param example 条件
     * @param page 分页信息
     */
    public List queryEntitiesByTemplateWithPage(TGeneralprocessModelfour example, Page page) {
        List<TGeneralprocessModelfour> result = (List<TGeneralprocessModelfour>)queryForList("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_queryEntitiesByTemplate", example,page);
        return result;
    }

    /**
     * 通过查询实例，删除数据
     * @abatorgenerated
     */
    public int deleteByExample(TGeneralprocessModelfourExample example) {
        int rows = getSqlMapClientTemplate().delete("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * 根据Bean数据模板查询条件更新记录
     * @abatorgenerated
     * @param example 条件
     */
    public int deleteByTemplate(TGeneralprocessModelfour example) {
        int rows = getSqlMapClientTemplate().delete("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_deleteByTemplate", example);
        return rows;
    }

    /**
     * 通过查询实例，统计总数
     * @abatorgenerated
     */
    public int countByExample(TGeneralprocessModelfourExample example) {
        Integer count = (Integer)  queryForObject("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * 通过查询Bean数据模板，统计总数
     * @abatorgenerated
     * @param example 条件
     */
    public int countByTemplate(TGeneralprocessModelfour example) {
        Integer rows = (Integer)queryForObject("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_countByTemplate", example);
        return rows.intValue();
    }

    /**
     * 通过查询实例，更新非null字段
     * @abatorgenerated
     */
    public int updateByExampleSelective(TGeneralprocessModelfour record, TGeneralprocessModelfourExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * 通过查询实例，更新全部字段
     * @abatorgenerated
     */
    public int updateByExample(TGeneralprocessModelfour record, TGeneralprocessModelfourExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * 根据Bean数据模板查询条件更新记录
     * @abatorgenerated
     * @param record 值
     * @param example 条件
     */
    public int updateEntityByTemplate(TGeneralprocessModelfour record, TGeneralprocessModelfour example) {
        HashMap<String,TGeneralprocessModelfour> params = new HashMap<String,TGeneralprocessModelfour>();
        params.put("record", record);
        params.put("template", example);
        int rows = getSqlMapClientTemplate().update("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_updateEntityByTemplate", params);
        return rows;
    }

    /**
     * 分页查询信息
     * @abatorgenerated
     */
    public List selectByDynamic(HashMap map, Page page) throws Exception {
        List list = queryForList("T_GENERALPROCESS_MODELFOUR_SqlMap.abatorgenerated_selectByDynamic", map, page);
        return list;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_GENERALPROCESS_MODELFOUR
     *
     * @abatorgenerated 
     */
    private static class UpdateByExampleParms extends TGeneralprocessModelfourExample {
        private Object record;

        public UpdateByExampleParms(Object record, TGeneralprocessModelfourExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public ProcessModelFour queryModelFour(HashMap<String, Object> map) {
		return (ProcessModelFour) getSqlMapClientTemplate().queryForObject("T_GENERALPROCESS_MODELFOUR_SqlMap.queryModelFour", map);
	}

	@Override
	public void addModelFour(ProcessModelFour modelFour) {
		getSqlMapClientTemplate().insert("T_GENERALPROCESS_MODELFOUR_SqlMap.addModelFour", modelFour);
	}

	@Override
	public void uptModelFour(ProcessModelFour modelFour) {
		getSqlMapClientTemplate().update("T_GENERALPROCESS_MODELFOUR_SqlMap.uptModelFour", modelFour);
	}

	@Override
	public ProcessModelFour queryModelFourById(String processModelId) {
		HashMap<String, Object> map = new HashMap<String, Object>();
		map.put("processModelId", processModelId);
		return (ProcessModelFour) queryForObject("T_GENERALPROCESS_MODELFOUR_SqlMap.queryModelFourById", map);
	}
}