package com.gotop.Generalprocess.dao.impl;

import com.gotop.Generalprocess.dao.ITGeneralprocessModeleightDAO;
import com.gotop.Generalprocess.model.ProcessModelEight;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import org.apache.log4j.Logger;

public class TGeneralprocessModeleightDAO extends SqlMapClientDao implements ITGeneralprocessModeleightDAO {
    /**
	 * @abatorgenerated
	 */
	protected Logger log = Logger.getLogger(TGeneralprocessModeleightDAO.class);

	/**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table T_GENERALPROCESS_MODELEIGTH
     *
     * @abatorgenerated 
     */
    public TGeneralprocessModeleightDAO() {
        super();
    }

    
	@Override
	public ProcessModelEight queryModelEight(HashMap<String, Object> map) {
		// TODO Auto-generated method stub
		return (ProcessModelEight) queryForObject("T_GENERALPROCESS_MODELEight_SqlMap.queryModelEight", map);
	}


	@Override
	public void uptModelEight(ProcessModelEight modelEight) {
		// TODO Auto-generated method stub
		getSqlMapClientTemplate().update("T_GENERALPROCESS_MODELEIGHT_SqlMap.uptModelEight", modelEight);
	}


	@Override
	public void addModelEight(ProcessModelEight modelEight) {
		// TODO Auto-generated method stub
		getSqlMapClientTemplate().insert("T_GENERALPROCESS_MODELEIGHT_SqlMap.addModelEight", modelEight);
	}

	@Override
	public ProcessModelEight queryModelEightById(String processModelId) {
		HashMap<String, Object> map = new HashMap<String, Object>();
		map.put("processModelId", processModelId);
		return (ProcessModelEight) queryForObject("T_GENERALPROCESS_MODELTHREE_SqlMap.queryModelEightById", map);
	}
   
	
}