package com.gotop.Generalprocess.dao.impl;

import com.gotop.Generalprocess.dao.ITGeneralprocessCdtypeDAO;
import com.gotop.Generalprocess.model.TGeneralprocessCdtype;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import org.apache.log4j.Logger;

public class TGeneralprocessCdtypeDAO extends SqlMapClientDao implements ITGeneralprocessCdtypeDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TGeneralprocessCdtypeDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table T_GENERALPROCESS_CDTYPE
     *
     * @abatorgenerated 
     */
    public TGeneralprocessCdtypeDAO() {
        super();
    }

	@Override
	public List<TGeneralprocessCdtype> queryPageCdtype(
			TGeneralprocessCdtype cdtype,Page page) {
		// TODO Auto-generated method stub
		List<TGeneralprocessCdtype> list = (List<TGeneralprocessCdtype>)queryForList("T_GENERALPROCESS_CDTYPE_SqlMap.queryCdtypes", cdtype, page);
        return list;
	}

	@Override
	public List<TGeneralprocessCdtype> querycreditType(
			TGeneralprocessCdtype cdtype) {
		// TODO Auto-generated method stub
		HashMap<String, Object> map = new HashMap<String, Object>();
		map.put("firstClass", cdtype.getFirstClass());
		List<TGeneralprocessCdtype> list = (List<TGeneralprocessCdtype>)queryForList("T_GENERALPROCESS_CDTYPE_SqlMap.querycreditType", map);
        return list;
	}
}