package com.gotop.timeMachine.dao.impl;

import com.gotop.timeMachine.dao.ITModelTimedayDAO;
import com.gotop.timeMachine.model.TModelTimeday;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;
import java.util.HashMap;
import java.util.List;
import org.apache.log4j.Logger;

public class TModelTimedayDAO extends SqlMapClientDao implements ITModelTimedayDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TModelTimedayDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table T_MODEL_TIMEDAY
     *
     * @abatorgenerated 
     */
    public TModelTimedayDAO() {
        super();
    }


    /**
     * 分页查询信息
     * @abatorgenerated
     */
    public List queryWorkDayListWithPage(TModelTimeday day, Page page) throws Exception {
        List list = queryForList("T_MODEL_TIMEDAY_SqlMap.queryWorkDayListWithPage", day, page);
        return list;
    }


	@Override
	public List checkDayTime(TModelTimeday day) {
		 List list = queryForList("T_MODEL_TIMEDAY_SqlMap.checkDayTime", day);
	        return list;
	}


	@Override
	public void insertWorkDay(TModelTimeday day) {
		getSqlMapClientTemplate().insert("T_MODEL_TIMEDAY_SqlMap.insertWorkDay", day);
	}


	@Override
	public void updateWorkDayById(TModelTimeday day) {
		getSqlMapClientTemplate().update("T_MODEL_TIMEDAY_SqlMap.updateWorkDayById", day);
	}


	@Override
	public void delWorkDayById(TModelTimeday day) {
		getSqlMapClientTemplate().delete("T_MODEL_TIMEDAY_SqlMap.delWorkDayById", day);
	}


	@Override
	public List queryWorkDayById(TModelTimeday day) {
		List list = queryForList("T_MODEL_TIMEDAY_SqlMap.queryWorkDayById", day);
        return list;
	}

}