package com.gotop.modeFile.dao.impl;

import com.gotop.file.model.TFileResourceTable;
import com.gotop.modeFile.dao.ITModelFileDAO;
import com.gotop.modeFile.model.TModelFile;
import com.gotop.modeFile.model.TModelFileExample;
import com.gotop.util.dataSource.SqlMapClientDao;
import com.primeton.utils.Page;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import org.apache.log4j.Logger;

public class TModelFileDAO extends SqlMapClientDao implements ITModelFileDAO {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TModelFileDAO.class);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table T_MODEL_FILE
     *
     * @abatorgenerated 
     */
    public TModelFileDAO() {
        super();
    }

    /**
     * 插入一条新数据.
     * @abatorgenerated
     */
    public void insert(TModelFile record) {
        getSqlMapClientTemplate().insert("T_MODEL_FILE_SqlMap.abatorgenerated_insert", record);
    }

	@Override
	public List<TModelFile> queryFileById(String executionId,String modeId,String modeType) {
		HashMap<String, Object> map = new HashMap<String, Object>();
		map.put("executionId", executionId);
		map.put("modeId", modeId);
		map.put("modeType", modeType);
		//List<TFileResourceTable> fileList = queryForList("T_FILE_RESOURCE_TABLE_SqlMap.queryFileByIdandType", map);
		List<TModelFile>fileList=(List)queryForList("T_MODEL_FILE_SqlMap.abatorgenerated_iselect",map);
		return fileList;
	}

	@Override
	public TModelFile getFileResource(String fileId) {
  
		TModelFile tModelFile=new TModelFile();
		BigDecimal bd=new BigDecimal(fileId);
		tModelFile.setFileId(bd);
/*		tModelFile.setExecutionId(executionId);
		tModelFile.setModeId(modeId);
		tModelFile.setModeType(modeType);*/
		tModelFile=(TModelFile)queryForObject("T_MODEL_FILE_SqlMap.abatorgenerated_selectByPrimaryKey", tModelFile);
		return tModelFile;
	}

	@Override
	public void deleteFileToFileName(TModelFile file) throws Exception {
		// TODO Auto-generated method stub
		this.delete("T_MODEL_FILE_SqlMap.delete_file_from_filename",file);
	}

    
}