package com.gotop.Generalprocess.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TGeneralprocessModeloneExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TGeneralprocessModeloneExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** * @abatorgenerated  */
    public TGeneralprocessModeloneExample() {
        oredCriteria = new ArrayList();
    }

    /** * @abatorgenerated  */
    protected TGeneralprocessModeloneExample(TGeneralprocessModeloneExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** * @abatorgenerated  */
    /** * @abatorgenerated  */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** * @abatorgenerated  */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** * @abatorgenerated  */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** * @abatorgenerated  */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** * @abatorgenerated  */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_GENERALPROCESS_MODELONE
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andProcessmodeloneidIsNull() {
            addCriterion("PROCESSMODELONEID is null");
            return this;
        }

        public Criteria andProcessmodeloneidIsNotNull() {
            addCriterion("PROCESSMODELONEID is not null");
            return this;
        }

        public Criteria andProcessmodeloneidEqualTo(BigDecimal value) {
            addCriterion("PROCESSMODELONEID =", value, "processmodeloneid");
            return this;
        }

        public Criteria andProcessmodeloneidNotEqualTo(BigDecimal value) {
            addCriterion("PROCESSMODELONEID <>", value, "processmodeloneid");
            return this;
        }

        public Criteria andProcessmodeloneidGreaterThan(BigDecimal value) {
            addCriterion("PROCESSMODELONEID >", value, "processmodeloneid");
            return this;
        }

        public Criteria andProcessmodeloneidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PROCESSMODELONEID >=", value, "processmodeloneid");
            return this;
        }

        public Criteria andProcessmodeloneidLessThan(BigDecimal value) {
            addCriterion("PROCESSMODELONEID <", value, "processmodeloneid");
            return this;
        }

        public Criteria andProcessmodeloneidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PROCESSMODELONEID <=", value, "processmodeloneid");
            return this;
        }

        public Criteria andProcessmodeloneidIn(List values) {
            addCriterion("PROCESSMODELONEID in", values, "processmodeloneid");
            return this;
        }

        public Criteria andProcessmodeloneidNotIn(List values) {
            addCriterion("PROCESSMODELONEID not in", values, "processmodeloneid");
            return this;
        }

        public Criteria andProcessmodeloneidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROCESSMODELONEID between", value1, value2, "processmodeloneid");
            return this;
        }

        public Criteria andProcessmodeloneidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROCESSMODELONEID not between", value1, value2, "processmodeloneid");
            return this;
        }

        public Criteria andFlowIdIsNull() {
            addCriterion("FLOW_ID is null");
            return this;
        }

        public Criteria andFlowIdIsNotNull() {
            addCriterion("FLOW_ID is not null");
            return this;
        }

        public Criteria andFlowIdEqualTo(BigDecimal value) {
            addCriterion("FLOW_ID =", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotEqualTo(BigDecimal value) {
            addCriterion("FLOW_ID <>", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThan(BigDecimal value) {
            addCriterion("FLOW_ID >", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FLOW_ID >=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThan(BigDecimal value) {
            addCriterion("FLOW_ID <", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FLOW_ID <=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdIn(List values) {
            addCriterion("FLOW_ID in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdNotIn(List values) {
            addCriterion("FLOW_ID not in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FLOW_ID between", value1, value2, "flowId");
            return this;
        }

        public Criteria andFlowIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FLOW_ID not between", value1, value2, "flowId");
            return this;
        }

        public Criteria andOrgcodeoneIsNull() {
            addCriterion("ORGCODEONE is null");
            return this;
        }

        public Criteria andOrgcodeoneIsNotNull() {
            addCriterion("ORGCODEONE is not null");
            return this;
        }

        public Criteria andOrgcodeoneEqualTo(String value) {
            addCriterion("ORGCODEONE =", value, "orgcodeone");
            return this;
        }

        public Criteria andOrgcodeoneNotEqualTo(String value) {
            addCriterion("ORGCODEONE <>", value, "orgcodeone");
            return this;
        }

        public Criteria andOrgcodeoneGreaterThan(String value) {
            addCriterion("ORGCODEONE >", value, "orgcodeone");
            return this;
        }

        public Criteria andOrgcodeoneGreaterThanOrEqualTo(String value) {
            addCriterion("ORGCODEONE >=", value, "orgcodeone");
            return this;
        }

        public Criteria andOrgcodeoneLessThan(String value) {
            addCriterion("ORGCODEONE <", value, "orgcodeone");
            return this;
        }

        public Criteria andOrgcodeoneLessThanOrEqualTo(String value) {
            addCriterion("ORGCODEONE <=", value, "orgcodeone");
            return this;
        }

        public Criteria andOrgcodeoneLike(String value) {
            addCriterion("ORGCODEONE like", value, "orgcodeone");
            return this;
        }

        public Criteria andOrgcodeoneNotLike(String value) {
            addCriterion("ORGCODEONE not like", value, "orgcodeone");
            return this;
        }

        public Criteria andOrgcodeoneIn(List values) {
            addCriterion("ORGCODEONE in", values, "orgcodeone");
            return this;
        }

        public Criteria andOrgcodeoneNotIn(List values) {
            addCriterion("ORGCODEONE not in", values, "orgcodeone");
            return this;
        }

        public Criteria andOrgcodeoneBetween(String value1, String value2) {
            addCriterion("ORGCODEONE between", value1, value2, "orgcodeone");
            return this;
        }

        public Criteria andOrgcodeoneNotBetween(String value1, String value2) {
            addCriterion("ORGCODEONE not between", value1, value2, "orgcodeone");
            return this;
        }

        public Criteria andOrgcodetwoIsNull() {
            addCriterion("ORGCODETWO is null");
            return this;
        }

        public Criteria andOrgcodetwoIsNotNull() {
            addCriterion("ORGCODETWO is not null");
            return this;
        }

        public Criteria andOrgcodetwoEqualTo(String value) {
            addCriterion("ORGCODETWO =", value, "orgcodetwo");
            return this;
        }

        public Criteria andOrgcodetwoNotEqualTo(String value) {
            addCriterion("ORGCODETWO <>", value, "orgcodetwo");
            return this;
        }

        public Criteria andOrgcodetwoGreaterThan(String value) {
            addCriterion("ORGCODETWO >", value, "orgcodetwo");
            return this;
        }

        public Criteria andOrgcodetwoGreaterThanOrEqualTo(String value) {
            addCriterion("ORGCODETWO >=", value, "orgcodetwo");
            return this;
        }

        public Criteria andOrgcodetwoLessThan(String value) {
            addCriterion("ORGCODETWO <", value, "orgcodetwo");
            return this;
        }

        public Criteria andOrgcodetwoLessThanOrEqualTo(String value) {
            addCriterion("ORGCODETWO <=", value, "orgcodetwo");
            return this;
        }

        public Criteria andOrgcodetwoLike(String value) {
            addCriterion("ORGCODETWO like", value, "orgcodetwo");
            return this;
        }

        public Criteria andOrgcodetwoNotLike(String value) {
            addCriterion("ORGCODETWO not like", value, "orgcodetwo");
            return this;
        }

        public Criteria andOrgcodetwoIn(List values) {
            addCriterion("ORGCODETWO in", values, "orgcodetwo");
            return this;
        }

        public Criteria andOrgcodetwoNotIn(List values) {
            addCriterion("ORGCODETWO not in", values, "orgcodetwo");
            return this;
        }

        public Criteria andOrgcodetwoBetween(String value1, String value2) {
            addCriterion("ORGCODETWO between", value1, value2, "orgcodetwo");
            return this;
        }

        public Criteria andOrgcodetwoNotBetween(String value1, String value2) {
            addCriterion("ORGCODETWO not between", value1, value2, "orgcodetwo");
            return this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return this;
        }

        public Criteria andCreatorIn(List values) {
            addCriterion("CREATOR in", values, "creator");
            return this;
        }

        public Criteria andCreatorNotIn(List values) {
            addCriterion("CREATOR not in", values, "creator");
            return this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return this;
        }

        public Criteria andFdxdyIsNull() {
            addCriterion("FDXDY is null");
            return this;
        }

        public Criteria andFdxdyIsNotNull() {
            addCriterion("FDXDY is not null");
            return this;
        }

        public Criteria andFdxdyEqualTo(String value) {
            addCriterion("FDXDY =", value, "fdxdy");
            return this;
        }

        public Criteria andFdxdyNotEqualTo(String value) {
            addCriterion("FDXDY <>", value, "fdxdy");
            return this;
        }

        public Criteria andFdxdyGreaterThan(String value) {
            addCriterion("FDXDY >", value, "fdxdy");
            return this;
        }

        public Criteria andFdxdyGreaterThanOrEqualTo(String value) {
            addCriterion("FDXDY >=", value, "fdxdy");
            return this;
        }

        public Criteria andFdxdyLessThan(String value) {
            addCriterion("FDXDY <", value, "fdxdy");
            return this;
        }

        public Criteria andFdxdyLessThanOrEqualTo(String value) {
            addCriterion("FDXDY <=", value, "fdxdy");
            return this;
        }

        public Criteria andFdxdyLike(String value) {
            addCriterion("FDXDY like", value, "fdxdy");
            return this;
        }

        public Criteria andFdxdyNotLike(String value) {
            addCriterion("FDXDY not like", value, "fdxdy");
            return this;
        }

        public Criteria andFdxdyIn(List values) {
            addCriterion("FDXDY in", values, "fdxdy");
            return this;
        }

        public Criteria andFdxdyNotIn(List values) {
            addCriterion("FDXDY not in", values, "fdxdy");
            return this;
        }

        public Criteria andFdxdyBetween(String value1, String value2) {
            addCriterion("FDXDY between", value1, value2, "fdxdy");
            return this;
        }

        public Criteria andFdxdyNotBetween(String value1, String value2) {
            addCriterion("FDXDY not between", value1, value2, "fdxdy");
            return this;
        }

        public Criteria andYxzgIsNull() {
            addCriterion("YXZG is null");
            return this;
        }

        public Criteria andYxzgIsNotNull() {
            addCriterion("YXZG is not null");
            return this;
        }

        public Criteria andYxzgEqualTo(String value) {
            addCriterion("YXZG =", value, "yxzg");
            return this;
        }

        public Criteria andYxzgNotEqualTo(String value) {
            addCriterion("YXZG <>", value, "yxzg");
            return this;
        }

        public Criteria andYxzgGreaterThan(String value) {
            addCriterion("YXZG >", value, "yxzg");
            return this;
        }

        public Criteria andYxzgGreaterThanOrEqualTo(String value) {
            addCriterion("YXZG >=", value, "yxzg");
            return this;
        }

        public Criteria andYxzgLessThan(String value) {
            addCriterion("YXZG <", value, "yxzg");
            return this;
        }

        public Criteria andYxzgLessThanOrEqualTo(String value) {
            addCriterion("YXZG <=", value, "yxzg");
            return this;
        }

        public Criteria andYxzgLike(String value) {
            addCriterion("YXZG like", value, "yxzg");
            return this;
        }

        public Criteria andYxzgNotLike(String value) {
            addCriterion("YXZG not like", value, "yxzg");
            return this;
        }

        public Criteria andYxzgIn(List values) {
            addCriterion("YXZG in", values, "yxzg");
            return this;
        }

        public Criteria andYxzgNotIn(List values) {
            addCriterion("YXZG not in", values, "yxzg");
            return this;
        }

        public Criteria andYxzgBetween(String value1, String value2) {
            addCriterion("YXZG between", value1, value2, "yxzg");
            return this;
        }

        public Criteria andYxzgNotBetween(String value1, String value2) {
            addCriterion("YXZG not between", value1, value2, "yxzg");
            return this;
        }

        public Criteria andYxryIsNull() {
            addCriterion("YXRY is null");
            return this;
        }

        public Criteria andYxryIsNotNull() {
            addCriterion("YXRY is not null");
            return this;
        }

        public Criteria andYxryEqualTo(String value) {
            addCriterion("YXRY =", value, "yxry");
            return this;
        }

        public Criteria andYxryNotEqualTo(String value) {
            addCriterion("YXRY <>", value, "yxry");
            return this;
        }

        public Criteria andYxryGreaterThan(String value) {
            addCriterion("YXRY >", value, "yxry");
            return this;
        }

        public Criteria andYxryGreaterThanOrEqualTo(String value) {
            addCriterion("YXRY >=", value, "yxry");
            return this;
        }

        public Criteria andYxryLessThan(String value) {
            addCriterion("YXRY <", value, "yxry");
            return this;
        }

        public Criteria andYxryLessThanOrEqualTo(String value) {
            addCriterion("YXRY <=", value, "yxry");
            return this;
        }

        public Criteria andYxryLike(String value) {
            addCriterion("YXRY like", value, "yxry");
            return this;
        }

        public Criteria andYxryNotLike(String value) {
            addCriterion("YXRY not like", value, "yxry");
            return this;
        }

        public Criteria andYxryIn(List values) {
            addCriterion("YXRY in", values, "yxry");
            return this;
        }

        public Criteria andYxryNotIn(List values) {
            addCriterion("YXRY not in", values, "yxry");
            return this;
        }

        public Criteria andYxryBetween(String value1, String value2) {
            addCriterion("YXRY between", value1, value2, "yxry");
            return this;
        }

        public Criteria andYxryNotBetween(String value1, String value2) {
            addCriterion("YXRY not between", value1, value2, "yxry");
            return this;
        }

        public Criteria andCurrencyIsNull() {
            addCriterion("CURRENCY is null");
            return this;
        }

        public Criteria andCurrencyIsNotNull() {
            addCriterion("CURRENCY is not null");
            return this;
        }

        public Criteria andCurrencyEqualTo(String value) {
            addCriterion("CURRENCY =", value, "currency");
            return this;
        }

        public Criteria andCurrencyNotEqualTo(String value) {
            addCriterion("CURRENCY <>", value, "currency");
            return this;
        }

        public Criteria andCurrencyGreaterThan(String value) {
            addCriterion("CURRENCY >", value, "currency");
            return this;
        }

        public Criteria andCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENCY >=", value, "currency");
            return this;
        }

        public Criteria andCurrencyLessThan(String value) {
            addCriterion("CURRENCY <", value, "currency");
            return this;
        }

        public Criteria andCurrencyLessThanOrEqualTo(String value) {
            addCriterion("CURRENCY <=", value, "currency");
            return this;
        }

        public Criteria andCurrencyLike(String value) {
            addCriterion("CURRENCY like", value, "currency");
            return this;
        }

        public Criteria andCurrencyNotLike(String value) {
            addCriterion("CURRENCY not like", value, "currency");
            return this;
        }

        public Criteria andCurrencyIn(List values) {
            addCriterion("CURRENCY in", values, "currency");
            return this;
        }

        public Criteria andCurrencyNotIn(List values) {
            addCriterion("CURRENCY not in", values, "currency");
            return this;
        }

        public Criteria andCurrencyBetween(String value1, String value2) {
            addCriterion("CURRENCY between", value1, value2, "currency");
            return this;
        }

        public Criteria andCurrencyNotBetween(String value1, String value2) {
            addCriterion("CURRENCY not between", value1, value2, "currency");
            return this;
        }

        public Criteria andApplyBalIsNull() {
            addCriterion("APPLY_BAL is null");
            return this;
        }

        public Criteria andApplyBalIsNotNull() {
            addCriterion("APPLY_BAL is not null");
            return this;
        }

        public Criteria andApplyBalEqualTo(String value) {
            addCriterion("APPLY_BAL =", value, "applyBal");
            return this;
        }

        public Criteria andApplyBalNotEqualTo(String value) {
            addCriterion("APPLY_BAL <>", value, "applyBal");
            return this;
        }

        public Criteria andApplyBalGreaterThan(String value) {
            addCriterion("APPLY_BAL >", value, "applyBal");
            return this;
        }

        public Criteria andApplyBalGreaterThanOrEqualTo(String value) {
            addCriterion("APPLY_BAL >=", value, "applyBal");
            return this;
        }

        public Criteria andApplyBalLessThan(String value) {
            addCriterion("APPLY_BAL <", value, "applyBal");
            return this;
        }

        public Criteria andApplyBalLessThanOrEqualTo(String value) {
            addCriterion("APPLY_BAL <=", value, "applyBal");
            return this;
        }

        public Criteria andApplyBalLike(String value) {
            addCriterion("APPLY_BAL like", value, "applyBal");
            return this;
        }

        public Criteria andApplyBalNotLike(String value) {
            addCriterion("APPLY_BAL not like", value, "applyBal");
            return this;
        }

        public Criteria andApplyBalIn(List values) {
            addCriterion("APPLY_BAL in", values, "applyBal");
            return this;
        }

        public Criteria andApplyBalNotIn(List values) {
            addCriterion("APPLY_BAL not in", values, "applyBal");
            return this;
        }

        public Criteria andApplyBalBetween(String value1, String value2) {
            addCriterion("APPLY_BAL between", value1, value2, "applyBal");
            return this;
        }

        public Criteria andApplyBalNotBetween(String value1, String value2) {
            addCriterion("APPLY_BAL not between", value1, value2, "applyBal");
            return this;
        }

        public Criteria andOnecategoryIsNull() {
            addCriterion("ONECATEGORY is null");
            return this;
        }

        public Criteria andOnecategoryIsNotNull() {
            addCriterion("ONECATEGORY is not null");
            return this;
        }

        public Criteria andOnecategoryEqualTo(String value) {
            addCriterion("ONECATEGORY =", value, "onecategory");
            return this;
        }

        public Criteria andOnecategoryNotEqualTo(String value) {
            addCriterion("ONECATEGORY <>", value, "onecategory");
            return this;
        }

        public Criteria andOnecategoryGreaterThan(String value) {
            addCriterion("ONECATEGORY >", value, "onecategory");
            return this;
        }

        public Criteria andOnecategoryGreaterThanOrEqualTo(String value) {
            addCriterion("ONECATEGORY >=", value, "onecategory");
            return this;
        }

        public Criteria andOnecategoryLessThan(String value) {
            addCriterion("ONECATEGORY <", value, "onecategory");
            return this;
        }

        public Criteria andOnecategoryLessThanOrEqualTo(String value) {
            addCriterion("ONECATEGORY <=", value, "onecategory");
            return this;
        }

        public Criteria andOnecategoryLike(String value) {
            addCriterion("ONECATEGORY like", value, "onecategory");
            return this;
        }

        public Criteria andOnecategoryNotLike(String value) {
            addCriterion("ONECATEGORY not like", value, "onecategory");
            return this;
        }

        public Criteria andOnecategoryIn(List values) {
            addCriterion("ONECATEGORY in", values, "onecategory");
            return this;
        }

        public Criteria andOnecategoryNotIn(List values) {
            addCriterion("ONECATEGORY not in", values, "onecategory");
            return this;
        }

        public Criteria andOnecategoryBetween(String value1, String value2) {
            addCriterion("ONECATEGORY between", value1, value2, "onecategory");
            return this;
        }

        public Criteria andOnecategoryNotBetween(String value1, String value2) {
            addCriterion("ONECATEGORY not between", value1, value2, "onecategory");
            return this;
        }

        public Criteria andLoancategoryIsNull() {
            addCriterion("LOANCATEGORY is null");
            return this;
        }

        public Criteria andLoancategoryIsNotNull() {
            addCriterion("LOANCATEGORY is not null");
            return this;
        }

        public Criteria andLoancategoryEqualTo(String value) {
            addCriterion("LOANCATEGORY =", value, "loancategory");
            return this;
        }

        public Criteria andLoancategoryNotEqualTo(String value) {
            addCriterion("LOANCATEGORY <>", value, "loancategory");
            return this;
        }

        public Criteria andLoancategoryGreaterThan(String value) {
            addCriterion("LOANCATEGORY >", value, "loancategory");
            return this;
        }

        public Criteria andLoancategoryGreaterThanOrEqualTo(String value) {
            addCriterion("LOANCATEGORY >=", value, "loancategory");
            return this;
        }

        public Criteria andLoancategoryLessThan(String value) {
            addCriterion("LOANCATEGORY <", value, "loancategory");
            return this;
        }

        public Criteria andLoancategoryLessThanOrEqualTo(String value) {
            addCriterion("LOANCATEGORY <=", value, "loancategory");
            return this;
        }

        public Criteria andLoancategoryLike(String value) {
            addCriterion("LOANCATEGORY like", value, "loancategory");
            return this;
        }

        public Criteria andLoancategoryNotLike(String value) {
            addCriterion("LOANCATEGORY not like", value, "loancategory");
            return this;
        }

        public Criteria andLoancategoryIn(List values) {
            addCriterion("LOANCATEGORY in", values, "loancategory");
            return this;
        }

        public Criteria andLoancategoryNotIn(List values) {
            addCriterion("LOANCATEGORY not in", values, "loancategory");
            return this;
        }

        public Criteria andLoancategoryBetween(String value1, String value2) {
            addCriterion("LOANCATEGORY between", value1, value2, "loancategory");
            return this;
        }

        public Criteria andLoancategoryNotBetween(String value1, String value2) {
            addCriterion("LOANCATEGORY not between", value1, value2, "loancategory");
            return this;
        }

        public Criteria andDywxNameIsNull() {
            addCriterion("DYWX_NAME is null");
            return this;
        }

        public Criteria andDywxNameIsNotNull() {
            addCriterion("DYWX_NAME is not null");
            return this;
        }

        public Criteria andDywxNameEqualTo(String value) {
            addCriterion("DYWX_NAME =", value, "dywxName");
            return this;
        }

        public Criteria andDywxNameNotEqualTo(String value) {
            addCriterion("DYWX_NAME <>", value, "dywxName");
            return this;
        }

        public Criteria andDywxNameGreaterThan(String value) {
            addCriterion("DYWX_NAME >", value, "dywxName");
            return this;
        }

        public Criteria andDywxNameGreaterThanOrEqualTo(String value) {
            addCriterion("DYWX_NAME >=", value, "dywxName");
            return this;
        }

        public Criteria andDywxNameLessThan(String value) {
            addCriterion("DYWX_NAME <", value, "dywxName");
            return this;
        }

        public Criteria andDywxNameLessThanOrEqualTo(String value) {
            addCriterion("DYWX_NAME <=", value, "dywxName");
            return this;
        }

        public Criteria andDywxNameLike(String value) {
            addCriterion("DYWX_NAME like", value, "dywxName");
            return this;
        }

        public Criteria andDywxNameNotLike(String value) {
            addCriterion("DYWX_NAME not like", value, "dywxName");
            return this;
        }

        public Criteria andDywxNameIn(List values) {
            addCriterion("DYWX_NAME in", values, "dywxName");
            return this;
        }

        public Criteria andDywxNameNotIn(List values) {
            addCriterion("DYWX_NAME not in", values, "dywxName");
            return this;
        }

        public Criteria andDywxNameBetween(String value1, String value2) {
            addCriterion("DYWX_NAME between", value1, value2, "dywxName");
            return this;
        }

        public Criteria andDywxNameNotBetween(String value1, String value2) {
            addCriterion("DYWX_NAME not between", value1, value2, "dywxName");
            return this;
        }

        public Criteria andCoorganizationIsNull() {
            addCriterion("COORGANIZATION is null");
            return this;
        }

        public Criteria andCoorganizationIsNotNull() {
            addCriterion("COORGANIZATION is not null");
            return this;
        }

        public Criteria andCoorganizationEqualTo(String value) {
            addCriterion("COORGANIZATION =", value, "coorganization");
            return this;
        }

        public Criteria andCoorganizationNotEqualTo(String value) {
            addCriterion("COORGANIZATION <>", value, "coorganization");
            return this;
        }

        public Criteria andCoorganizationGreaterThan(String value) {
            addCriterion("COORGANIZATION >", value, "coorganization");
            return this;
        }

        public Criteria andCoorganizationGreaterThanOrEqualTo(String value) {
            addCriterion("COORGANIZATION >=", value, "coorganization");
            return this;
        }

        public Criteria andCoorganizationLessThan(String value) {
            addCriterion("COORGANIZATION <", value, "coorganization");
            return this;
        }

        public Criteria andCoorganizationLessThanOrEqualTo(String value) {
            addCriterion("COORGANIZATION <=", value, "coorganization");
            return this;
        }

        public Criteria andCoorganizationLike(String value) {
            addCriterion("COORGANIZATION like", value, "coorganization");
            return this;
        }

        public Criteria andCoorganizationNotLike(String value) {
            addCriterion("COORGANIZATION not like", value, "coorganization");
            return this;
        }

        public Criteria andCoorganizationIn(List values) {
            addCriterion("COORGANIZATION in", values, "coorganization");
            return this;
        }

        public Criteria andCoorganizationNotIn(List values) {
            addCriterion("COORGANIZATION not in", values, "coorganization");
            return this;
        }

        public Criteria andCoorganizationBetween(String value1, String value2) {
            addCriterion("COORGANIZATION between", value1, value2, "coorganization");
            return this;
        }

        public Criteria andCoorganizationNotBetween(String value1, String value2) {
            addCriterion("COORGANIZATION not between", value1, value2, "coorganization");
            return this;
        }

        public Criteria andSurveyTimeIsNull() {
            addCriterion("SURVEY_TIME is null");
            return this;
        }

        public Criteria andSurveyTimeIsNotNull() {
            addCriterion("SURVEY_TIME is not null");
            return this;
        }

        public Criteria andSurveyTimeEqualTo(String value) {
            addCriterion("SURVEY_TIME =", value, "surveyTime");
            return this;
        }

        public Criteria andSurveyTimeNotEqualTo(String value) {
            addCriterion("SURVEY_TIME <>", value, "surveyTime");
            return this;
        }

        public Criteria andSurveyTimeGreaterThan(String value) {
            addCriterion("SURVEY_TIME >", value, "surveyTime");
            return this;
        }

        public Criteria andSurveyTimeGreaterThanOrEqualTo(String value) {
            addCriterion("SURVEY_TIME >=", value, "surveyTime");
            return this;
        }

        public Criteria andSurveyTimeLessThan(String value) {
            addCriterion("SURVEY_TIME <", value, "surveyTime");
            return this;
        }

        public Criteria andSurveyTimeLessThanOrEqualTo(String value) {
            addCriterion("SURVEY_TIME <=", value, "surveyTime");
            return this;
        }

        public Criteria andSurveyTimeLike(String value) {
            addCriterion("SURVEY_TIME like", value, "surveyTime");
            return this;
        }

        public Criteria andSurveyTimeNotLike(String value) {
            addCriterion("SURVEY_TIME not like", value, "surveyTime");
            return this;
        }

        public Criteria andSurveyTimeIn(List values) {
            addCriterion("SURVEY_TIME in", values, "surveyTime");
            return this;
        }

        public Criteria andSurveyTimeNotIn(List values) {
            addCriterion("SURVEY_TIME not in", values, "surveyTime");
            return this;
        }

        public Criteria andSurveyTimeBetween(String value1, String value2) {
            addCriterion("SURVEY_TIME between", value1, value2, "surveyTime");
            return this;
        }

        public Criteria andSurveyTimeNotBetween(String value1, String value2) {
            addCriterion("SURVEY_TIME not between", value1, value2, "surveyTime");
            return this;
        }

        public Criteria andContentIsNull() {
            addCriterion("CONTENT is null");
            return this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("CONTENT is not null");
            return this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("CONTENT =", value, "content");
            return this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("CONTENT <>", value, "content");
            return this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("CONTENT >", value, "content");
            return this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("CONTENT >=", value, "content");
            return this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("CONTENT <", value, "content");
            return this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("CONTENT <=", value, "content");
            return this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("CONTENT like", value, "content");
            return this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("CONTENT not like", value, "content");
            return this;
        }

        public Criteria andContentIn(List values) {
            addCriterion("CONTENT in", values, "content");
            return this;
        }

        public Criteria andContentNotIn(List values) {
            addCriterion("CONTENT not in", values, "content");
            return this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("CONTENT between", value1, value2, "content");
            return this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("CONTENT not between", value1, value2, "content");
            return this;
        }

        public Criteria andCustNameIsNull() {
            addCriterion("CUST_NAME is null");
            return this;
        }

        public Criteria andCustNameIsNotNull() {
            addCriterion("CUST_NAME is not null");
            return this;
        }

        public Criteria andCustNameEqualTo(String value) {
            addCriterion("CUST_NAME =", value, "custName");
            return this;
        }

        public Criteria andCustNameNotEqualTo(String value) {
            addCriterion("CUST_NAME <>", value, "custName");
            return this;
        }

        public Criteria andCustNameGreaterThan(String value) {
            addCriterion("CUST_NAME >", value, "custName");
            return this;
        }

        public Criteria andCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_NAME >=", value, "custName");
            return this;
        }

        public Criteria andCustNameLessThan(String value) {
            addCriterion("CUST_NAME <", value, "custName");
            return this;
        }

        public Criteria andCustNameLessThanOrEqualTo(String value) {
            addCriterion("CUST_NAME <=", value, "custName");
            return this;
        }

        public Criteria andCustNameLike(String value) {
            addCriterion("CUST_NAME like", value, "custName");
            return this;
        }

        public Criteria andCustNameNotLike(String value) {
            addCriterion("CUST_NAME not like", value, "custName");
            return this;
        }

        public Criteria andCustNameIn(List values) {
            addCriterion("CUST_NAME in", values, "custName");
            return this;
        }

        public Criteria andCustNameNotIn(List values) {
            addCriterion("CUST_NAME not in", values, "custName");
            return this;
        }

        public Criteria andCustNameBetween(String value1, String value2) {
            addCriterion("CUST_NAME between", value1, value2, "custName");
            return this;
        }

        public Criteria andCustNameNotBetween(String value1, String value2) {
            addCriterion("CUST_NAME not between", value1, value2, "custName");
            return this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return this;
        }

        public Criteria andCreateDateIn(List values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateNotIn(List values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateNameIsNull() {
            addCriterion("CREATE_NAME is null");
            return this;
        }

        public Criteria andCreateNameIsNotNull() {
            addCriterion("CREATE_NAME is not null");
            return this;
        }

        public Criteria andCreateNameEqualTo(String value) {
            addCriterion("CREATE_NAME =", value, "createName");
            return this;
        }

        public Criteria andCreateNameNotEqualTo(String value) {
            addCriterion("CREATE_NAME <>", value, "createName");
            return this;
        }

        public Criteria andCreateNameGreaterThan(String value) {
            addCriterion("CREATE_NAME >", value, "createName");
            return this;
        }

        public Criteria andCreateNameGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_NAME >=", value, "createName");
            return this;
        }

        public Criteria andCreateNameLessThan(String value) {
            addCriterion("CREATE_NAME <", value, "createName");
            return this;
        }

        public Criteria andCreateNameLessThanOrEqualTo(String value) {
            addCriterion("CREATE_NAME <=", value, "createName");
            return this;
        }

        public Criteria andCreateNameLike(String value) {
            addCriterion("CREATE_NAME like", value, "createName");
            return this;
        }

        public Criteria andCreateNameNotLike(String value) {
            addCriterion("CREATE_NAME not like", value, "createName");
            return this;
        }

        public Criteria andCreateNameIn(List values) {
            addCriterion("CREATE_NAME in", values, "createName");
            return this;
        }

        public Criteria andCreateNameNotIn(List values) {
            addCriterion("CREATE_NAME not in", values, "createName");
            return this;
        }

        public Criteria andCreateNameBetween(String value1, String value2) {
            addCriterion("CREATE_NAME between", value1, value2, "createName");
            return this;
        }

        public Criteria andCreateNameNotBetween(String value1, String value2) {
            addCriterion("CREATE_NAME not between", value1, value2, "createName");
            return this;
        }

        public Criteria andLastUpDateIsNull() {
            addCriterion("LAST_UP_DATE is null");
            return this;
        }

        public Criteria andLastUpDateIsNotNull() {
            addCriterion("LAST_UP_DATE is not null");
            return this;
        }

        public Criteria andLastUpDateEqualTo(String value) {
            addCriterion("LAST_UP_DATE =", value, "lastUpDate");
            return this;
        }

        public Criteria andLastUpDateNotEqualTo(String value) {
            addCriterion("LAST_UP_DATE <>", value, "lastUpDate");
            return this;
        }

        public Criteria andLastUpDateGreaterThan(String value) {
            addCriterion("LAST_UP_DATE >", value, "lastUpDate");
            return this;
        }

        public Criteria andLastUpDateGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UP_DATE >=", value, "lastUpDate");
            return this;
        }

        public Criteria andLastUpDateLessThan(String value) {
            addCriterion("LAST_UP_DATE <", value, "lastUpDate");
            return this;
        }

        public Criteria andLastUpDateLessThanOrEqualTo(String value) {
            addCriterion("LAST_UP_DATE <=", value, "lastUpDate");
            return this;
        }

        public Criteria andLastUpDateLike(String value) {
            addCriterion("LAST_UP_DATE like", value, "lastUpDate");
            return this;
        }

        public Criteria andLastUpDateNotLike(String value) {
            addCriterion("LAST_UP_DATE not like", value, "lastUpDate");
            return this;
        }

        public Criteria andLastUpDateIn(List values) {
            addCriterion("LAST_UP_DATE in", values, "lastUpDate");
            return this;
        }

        public Criteria andLastUpDateNotIn(List values) {
            addCriterion("LAST_UP_DATE not in", values, "lastUpDate");
            return this;
        }

        public Criteria andLastUpDateBetween(String value1, String value2) {
            addCriterion("LAST_UP_DATE between", value1, value2, "lastUpDate");
            return this;
        }

        public Criteria andLastUpDateNotBetween(String value1, String value2) {
            addCriterion("LAST_UP_DATE not between", value1, value2, "lastUpDate");
            return this;
        }

        public Criteria andLastUpTimeIsNull() {
            addCriterion("LAST_UP_TIME is null");
            return this;
        }

        public Criteria andLastUpTimeIsNotNull() {
            addCriterion("LAST_UP_TIME is not null");
            return this;
        }

        public Criteria andLastUpTimeEqualTo(String value) {
            addCriterion("LAST_UP_TIME =", value, "lastUpTime");
            return this;
        }

        public Criteria andLastUpTimeNotEqualTo(String value) {
            addCriterion("LAST_UP_TIME <>", value, "lastUpTime");
            return this;
        }

        public Criteria andLastUpTimeGreaterThan(String value) {
            addCriterion("LAST_UP_TIME >", value, "lastUpTime");
            return this;
        }

        public Criteria andLastUpTimeGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UP_TIME >=", value, "lastUpTime");
            return this;
        }

        public Criteria andLastUpTimeLessThan(String value) {
            addCriterion("LAST_UP_TIME <", value, "lastUpTime");
            return this;
        }

        public Criteria andLastUpTimeLessThanOrEqualTo(String value) {
            addCriterion("LAST_UP_TIME <=", value, "lastUpTime");
            return this;
        }

        public Criteria andLastUpTimeLike(String value) {
            addCriterion("LAST_UP_TIME like", value, "lastUpTime");
            return this;
        }

        public Criteria andLastUpTimeNotLike(String value) {
            addCriterion("LAST_UP_TIME not like", value, "lastUpTime");
            return this;
        }

        public Criteria andLastUpTimeIn(List values) {
            addCriterion("LAST_UP_TIME in", values, "lastUpTime");
            return this;
        }

        public Criteria andLastUpTimeNotIn(List values) {
            addCriterion("LAST_UP_TIME not in", values, "lastUpTime");
            return this;
        }

        public Criteria andLastUpTimeBetween(String value1, String value2) {
            addCriterion("LAST_UP_TIME between", value1, value2, "lastUpTime");
            return this;
        }

        public Criteria andLastUpTimeNotBetween(String value1, String value2) {
            addCriterion("LAST_UP_TIME not between", value1, value2, "lastUpTime");
            return this;
        }

        public Criteria andLastUpNameIsNull() {
            addCriterion("LAST_UP_NAME is null");
            return this;
        }

        public Criteria andLastUpNameIsNotNull() {
            addCriterion("LAST_UP_NAME is not null");
            return this;
        }

        public Criteria andLastUpNameEqualTo(String value) {
            addCriterion("LAST_UP_NAME =", value, "lastUpName");
            return this;
        }

        public Criteria andLastUpNameNotEqualTo(String value) {
            addCriterion("LAST_UP_NAME <>", value, "lastUpName");
            return this;
        }

        public Criteria andLastUpNameGreaterThan(String value) {
            addCriterion("LAST_UP_NAME >", value, "lastUpName");
            return this;
        }

        public Criteria andLastUpNameGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UP_NAME >=", value, "lastUpName");
            return this;
        }

        public Criteria andLastUpNameLessThan(String value) {
            addCriterion("LAST_UP_NAME <", value, "lastUpName");
            return this;
        }

        public Criteria andLastUpNameLessThanOrEqualTo(String value) {
            addCriterion("LAST_UP_NAME <=", value, "lastUpName");
            return this;
        }

        public Criteria andLastUpNameLike(String value) {
            addCriterion("LAST_UP_NAME like", value, "lastUpName");
            return this;
        }

        public Criteria andLastUpNameNotLike(String value) {
            addCriterion("LAST_UP_NAME not like", value, "lastUpName");
            return this;
        }

        public Criteria andLastUpNameIn(List values) {
            addCriterion("LAST_UP_NAME in", values, "lastUpName");
            return this;
        }

        public Criteria andLastUpNameNotIn(List values) {
            addCriterion("LAST_UP_NAME not in", values, "lastUpName");
            return this;
        }

        public Criteria andLastUpNameBetween(String value1, String value2) {
            addCriterion("LAST_UP_NAME between", value1, value2, "lastUpName");
            return this;
        }

        public Criteria andLastUpNameNotBetween(String value1, String value2) {
            addCriterion("LAST_UP_NAME not between", value1, value2, "lastUpName");
            return this;
        }
    }
}