package com.gotop.Generalprocess.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.log4j.Logger;

public class TGeneralprocessModelsixExample {
    /**
     * 
     * @abatorgenerated
     */
    protected Logger log = Logger.getLogger(TGeneralprocessModelsixExample.class);

    /**
     * 排序字段.
     * @abatorgenerated
     */
    protected String orderByClause;

    /**
     * sql条件.
     * @abatorgenerated
     */
    protected List oredCriteria;

    /**
     * 分页查询的起始行数.
     * @abatorgenerated
     */
    private Integer oracleStart;

    /**
     * 分页查询结束行数.
     * @abatorgenerated
     */
    private Integer oracleEnd;

    /** * @abatorgenerated  */
    public TGeneralprocessModelsixExample() {
        oredCriteria = new ArrayList();
    }

    /** * @abatorgenerated  */
    protected TGeneralprocessModelsixExample(TGeneralprocessModelsixExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.oracleStart = example.oracleStart;
        this.oracleEnd = example.oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /** * @abatorgenerated  */
    /** * @abatorgenerated  */
    public String getOrderByClause() {
        return orderByClause;
    }

    /** * @abatorgenerated  */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /** * @abatorgenerated  */
    public Integer getOracleStart() {
        return oracleStart;
    }

    /** * @abatorgenerated  */
    public void setOracleStart(Integer oracleStart) {
        this.oracleStart = oracleStart;
    }

    /** * @abatorgenerated  */
    public Integer getOracleEnd() {
        return oracleEnd;
    }

    /** * @abatorgenerated  */
    public void setOracleEnd(Integer oracleEnd) {
        this.oracleEnd = oracleEnd;
    }

    /**
     * 增加整个新查询条件(Criteria)，增加后以or方式查询.
     * @abatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * 创新新Criteria，如果为第一个则加入到Criteria列表。并且返回
     * @abatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * 仅创新新Criteria,并且返回
     * @abatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * 清除查询条件
     * @abatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table T_GENERALPROCESS_MODELSIX
     *
     * @abatorgenerated 
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andProcessmodelidIsNull() {
            addCriterion("PROCESSMODELID is null");
            return this;
        }

        public Criteria andProcessmodelidIsNotNull() {
            addCriterion("PROCESSMODELID is not null");
            return this;
        }

        public Criteria andProcessmodelidEqualTo(BigDecimal value) {
            addCriterion("PROCESSMODELID =", value, "processmodelid");
            return this;
        }

        public Criteria andProcessmodelidNotEqualTo(BigDecimal value) {
            addCriterion("PROCESSMODELID <>", value, "processmodelid");
            return this;
        }

        public Criteria andProcessmodelidGreaterThan(BigDecimal value) {
            addCriterion("PROCESSMODELID >", value, "processmodelid");
            return this;
        }

        public Criteria andProcessmodelidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PROCESSMODELID >=", value, "processmodelid");
            return this;
        }

        public Criteria andProcessmodelidLessThan(BigDecimal value) {
            addCriterion("PROCESSMODELID <", value, "processmodelid");
            return this;
        }

        public Criteria andProcessmodelidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PROCESSMODELID <=", value, "processmodelid");
            return this;
        }

        public Criteria andProcessmodelidIn(List values) {
            addCriterion("PROCESSMODELID in", values, "processmodelid");
            return this;
        }

        public Criteria andProcessmodelidNotIn(List values) {
            addCriterion("PROCESSMODELID not in", values, "processmodelid");
            return this;
        }

        public Criteria andProcessmodelidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROCESSMODELID between", value1, value2, "processmodelid");
            return this;
        }

        public Criteria andProcessmodelidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROCESSMODELID not between", value1, value2, "processmodelid");
            return this;
        }

        public Criteria andFlowIdIsNull() {
            addCriterion("FLOW_ID is null");
            return this;
        }

        public Criteria andFlowIdIsNotNull() {
            addCriterion("FLOW_ID is not null");
            return this;
        }

        public Criteria andFlowIdEqualTo(String value) {
            addCriterion("FLOW_ID =", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotEqualTo(String value) {
            addCriterion("FLOW_ID <>", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThan(String value) {
            addCriterion("FLOW_ID >", value, "flowId");
            return this;
        }

        public Criteria andFlowIdGreaterThanOrEqualTo(String value) {
            addCriterion("FLOW_ID >=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThan(String value) {
            addCriterion("FLOW_ID <", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLessThanOrEqualTo(String value) {
            addCriterion("FLOW_ID <=", value, "flowId");
            return this;
        }

        public Criteria andFlowIdLike(String value) {
            addCriterion("FLOW_ID like", value, "flowId");
            return this;
        }

        public Criteria andFlowIdNotLike(String value) {
            addCriterion("FLOW_ID not like", value, "flowId");
            return this;
        }

        public Criteria andFlowIdIn(List values) {
            addCriterion("FLOW_ID in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdNotIn(List values) {
            addCriterion("FLOW_ID not in", values, "flowId");
            return this;
        }

        public Criteria andFlowIdBetween(String value1, String value2) {
            addCriterion("FLOW_ID between", value1, value2, "flowId");
            return this;
        }

        public Criteria andFlowIdNotBetween(String value1, String value2) {
            addCriterion("FLOW_ID not between", value1, value2, "flowId");
            return this;
        }

        public Criteria andTasknameIsNull() {
            addCriterion("TASKNAME is null");
            return this;
        }

        public Criteria andTasknameIsNotNull() {
            addCriterion("TASKNAME is not null");
            return this;
        }

        public Criteria andTasknameEqualTo(String value) {
            addCriterion("TASKNAME =", value, "taskname");
            return this;
        }

        public Criteria andTasknameNotEqualTo(String value) {
            addCriterion("TASKNAME <>", value, "taskname");
            return this;
        }

        public Criteria andTasknameGreaterThan(String value) {
            addCriterion("TASKNAME >", value, "taskname");
            return this;
        }

        public Criteria andTasknameGreaterThanOrEqualTo(String value) {
            addCriterion("TASKNAME >=", value, "taskname");
            return this;
        }

        public Criteria andTasknameLessThan(String value) {
            addCriterion("TASKNAME <", value, "taskname");
            return this;
        }

        public Criteria andTasknameLessThanOrEqualTo(String value) {
            addCriterion("TASKNAME <=", value, "taskname");
            return this;
        }

        public Criteria andTasknameLike(String value) {
            addCriterion("TASKNAME like", value, "taskname");
            return this;
        }

        public Criteria andTasknameNotLike(String value) {
            addCriterion("TASKNAME not like", value, "taskname");
            return this;
        }

        public Criteria andTasknameIn(List values) {
            addCriterion("TASKNAME in", values, "taskname");
            return this;
        }

        public Criteria andTasknameNotIn(List values) {
            addCriterion("TASKNAME not in", values, "taskname");
            return this;
        }

        public Criteria andTasknameBetween(String value1, String value2) {
            addCriterion("TASKNAME between", value1, value2, "taskname");
            return this;
        }

        public Criteria andTasknameNotBetween(String value1, String value2) {
            addCriterion("TASKNAME not between", value1, value2, "taskname");
            return this;
        }

        public Criteria andOpinionIsNull() {
            addCriterion("OPINION is null");
            return this;
        }

        public Criteria andOpinionIsNotNull() {
            addCriterion("OPINION is not null");
            return this;
        }

        public Criteria andOpinionEqualTo(String value) {
            addCriterion("OPINION =", value, "opinion");
            return this;
        }

        public Criteria andOpinionNotEqualTo(String value) {
            addCriterion("OPINION <>", value, "opinion");
            return this;
        }

        public Criteria andOpinionGreaterThan(String value) {
            addCriterion("OPINION >", value, "opinion");
            return this;
        }

        public Criteria andOpinionGreaterThanOrEqualTo(String value) {
            addCriterion("OPINION >=", value, "opinion");
            return this;
        }

        public Criteria andOpinionLessThan(String value) {
            addCriterion("OPINION <", value, "opinion");
            return this;
        }

        public Criteria andOpinionLessThanOrEqualTo(String value) {
            addCriterion("OPINION <=", value, "opinion");
            return this;
        }

        public Criteria andOpinionLike(String value) {
            addCriterion("OPINION like", value, "opinion");
            return this;
        }

        public Criteria andOpinionNotLike(String value) {
            addCriterion("OPINION not like", value, "opinion");
            return this;
        }

        public Criteria andOpinionIn(List values) {
            addCriterion("OPINION in", values, "opinion");
            return this;
        }

        public Criteria andOpinionNotIn(List values) {
            addCriterion("OPINION not in", values, "opinion");
            return this;
        }

        public Criteria andOpinionBetween(String value1, String value2) {
            addCriterion("OPINION between", value1, value2, "opinion");
            return this;
        }

        public Criteria andOpinionNotBetween(String value1, String value2) {
            addCriterion("OPINION not between", value1, value2, "opinion");
            return this;
        }

        public Criteria andMortgageTimeIsNull() {
            addCriterion("MORTGAGE_TIME is null");
            return this;
        }

        public Criteria andMortgageTimeIsNotNull() {
            addCriterion("MORTGAGE_TIME is not null");
            return this;
        }

        public Criteria andMortgageTimeEqualTo(String value) {
            addCriterion("MORTGAGE_TIME =", value, "mortgageTime");
            return this;
        }

        public Criteria andMortgageTimeNotEqualTo(String value) {
            addCriterion("MORTGAGE_TIME <>", value, "mortgageTime");
            return this;
        }

        public Criteria andMortgageTimeGreaterThan(String value) {
            addCriterion("MORTGAGE_TIME >", value, "mortgageTime");
            return this;
        }

        public Criteria andMortgageTimeGreaterThanOrEqualTo(String value) {
            addCriterion("MORTGAGE_TIME >=", value, "mortgageTime");
            return this;
        }

        public Criteria andMortgageTimeLessThan(String value) {
            addCriterion("MORTGAGE_TIME <", value, "mortgageTime");
            return this;
        }

        public Criteria andMortgageTimeLessThanOrEqualTo(String value) {
            addCriterion("MORTGAGE_TIME <=", value, "mortgageTime");
            return this;
        }

        public Criteria andMortgageTimeLike(String value) {
            addCriterion("MORTGAGE_TIME like", value, "mortgageTime");
            return this;
        }

        public Criteria andMortgageTimeNotLike(String value) {
            addCriterion("MORTGAGE_TIME not like", value, "mortgageTime");
            return this;
        }

        public Criteria andMortgageTimeIn(List values) {
            addCriterion("MORTGAGE_TIME in", values, "mortgageTime");
            return this;
        }

        public Criteria andMortgageTimeNotIn(List values) {
            addCriterion("MORTGAGE_TIME not in", values, "mortgageTime");
            return this;
        }

        public Criteria andMortgageTimeBetween(String value1, String value2) {
            addCriterion("MORTGAGE_TIME between", value1, value2, "mortgageTime");
            return this;
        }

        public Criteria andMortgageTimeNotBetween(String value1, String value2) {
            addCriterion("MORTGAGE_TIME not between", value1, value2, "mortgageTime");
            return this;
        }

        public Criteria andReceiveTimeIsNull() {
            addCriterion("RECEIVE_TIME is null");
            return this;
        }

        public Criteria andReceiveTimeIsNotNull() {
            addCriterion("RECEIVE_TIME is not null");
            return this;
        }

        public Criteria andReceiveTimeEqualTo(String value) {
            addCriterion("RECEIVE_TIME =", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeNotEqualTo(String value) {
            addCriterion("RECEIVE_TIME <>", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeGreaterThan(String value) {
            addCriterion("RECEIVE_TIME >", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeGreaterThanOrEqualTo(String value) {
            addCriterion("RECEIVE_TIME >=", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeLessThan(String value) {
            addCriterion("RECEIVE_TIME <", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeLessThanOrEqualTo(String value) {
            addCriterion("RECEIVE_TIME <=", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeLike(String value) {
            addCriterion("RECEIVE_TIME like", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeNotLike(String value) {
            addCriterion("RECEIVE_TIME not like", value, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeIn(List values) {
            addCriterion("RECEIVE_TIME in", values, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeNotIn(List values) {
            addCriterion("RECEIVE_TIME not in", values, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeBetween(String value1, String value2) {
            addCriterion("RECEIVE_TIME between", value1, value2, "receiveTime");
            return this;
        }

        public Criteria andReceiveTimeNotBetween(String value1, String value2) {
            addCriterion("RECEIVE_TIME not between", value1, value2, "receiveTime");
            return this;
        }

        public Criteria andApplicationTimeIsNull() {
            addCriterion("APPLICATION_TIME is null");
            return this;
        }

        public Criteria andApplicationTimeIsNotNull() {
            addCriterion("APPLICATION_TIME is not null");
            return this;
        }

        public Criteria andApplicationTimeEqualTo(String value) {
            addCriterion("APPLICATION_TIME =", value, "applicationTime");
            return this;
        }

        public Criteria andApplicationTimeNotEqualTo(String value) {
            addCriterion("APPLICATION_TIME <>", value, "applicationTime");
            return this;
        }

        public Criteria andApplicationTimeGreaterThan(String value) {
            addCriterion("APPLICATION_TIME >", value, "applicationTime");
            return this;
        }

        public Criteria andApplicationTimeGreaterThanOrEqualTo(String value) {
            addCriterion("APPLICATION_TIME >=", value, "applicationTime");
            return this;
        }

        public Criteria andApplicationTimeLessThan(String value) {
            addCriterion("APPLICATION_TIME <", value, "applicationTime");
            return this;
        }

        public Criteria andApplicationTimeLessThanOrEqualTo(String value) {
            addCriterion("APPLICATION_TIME <=", value, "applicationTime");
            return this;
        }

        public Criteria andApplicationTimeLike(String value) {
            addCriterion("APPLICATION_TIME like", value, "applicationTime");
            return this;
        }

        public Criteria andApplicationTimeNotLike(String value) {
            addCriterion("APPLICATION_TIME not like", value, "applicationTime");
            return this;
        }

        public Criteria andApplicationTimeIn(List values) {
            addCriterion("APPLICATION_TIME in", values, "applicationTime");
            return this;
        }

        public Criteria andApplicationTimeNotIn(List values) {
            addCriterion("APPLICATION_TIME not in", values, "applicationTime");
            return this;
        }

        public Criteria andApplicationTimeBetween(String value1, String value2) {
            addCriterion("APPLICATION_TIME between", value1, value2, "applicationTime");
            return this;
        }

        public Criteria andApplicationTimeNotBetween(String value1, String value2) {
            addCriterion("APPLICATION_TIME not between", value1, value2, "applicationTime");
            return this;
        }

        public Criteria andIssuedTimeIsNull() {
            addCriterion("ISSUED_TIME is null");
            return this;
        }

        public Criteria andIssuedTimeIsNotNull() {
            addCriterion("ISSUED_TIME is not null");
            return this;
        }

        public Criteria andIssuedTimeEqualTo(String value) {
            addCriterion("ISSUED_TIME =", value, "issuedTime");
            return this;
        }

        public Criteria andIssuedTimeNotEqualTo(String value) {
            addCriterion("ISSUED_TIME <>", value, "issuedTime");
            return this;
        }

        public Criteria andIssuedTimeGreaterThan(String value) {
            addCriterion("ISSUED_TIME >", value, "issuedTime");
            return this;
        }

        public Criteria andIssuedTimeGreaterThanOrEqualTo(String value) {
            addCriterion("ISSUED_TIME >=", value, "issuedTime");
            return this;
        }

        public Criteria andIssuedTimeLessThan(String value) {
            addCriterion("ISSUED_TIME <", value, "issuedTime");
            return this;
        }

        public Criteria andIssuedTimeLessThanOrEqualTo(String value) {
            addCriterion("ISSUED_TIME <=", value, "issuedTime");
            return this;
        }

        public Criteria andIssuedTimeLike(String value) {
            addCriterion("ISSUED_TIME like", value, "issuedTime");
            return this;
        }

        public Criteria andIssuedTimeNotLike(String value) {
            addCriterion("ISSUED_TIME not like", value, "issuedTime");
            return this;
        }

        public Criteria andIssuedTimeIn(List values) {
            addCriterion("ISSUED_TIME in", values, "issuedTime");
            return this;
        }

        public Criteria andIssuedTimeNotIn(List values) {
            addCriterion("ISSUED_TIME not in", values, "issuedTime");
            return this;
        }

        public Criteria andIssuedTimeBetween(String value1, String value2) {
            addCriterion("ISSUED_TIME between", value1, value2, "issuedTime");
            return this;
        }

        public Criteria andIssuedTimeNotBetween(String value1, String value2) {
            addCriterion("ISSUED_TIME not between", value1, value2, "issuedTime");
            return this;
        }

        public Criteria andSupportCategoryIsNull() {
            addCriterion("SUPPORT_CATEGORY is null");
            return this;
        }

        public Criteria andSupportCategoryIsNotNull() {
            addCriterion("SUPPORT_CATEGORY is not null");
            return this;
        }

        public Criteria andSupportCategoryEqualTo(String value) {
            addCriterion("SUPPORT_CATEGORY =", value, "supportCategory");
            return this;
        }

        public Criteria andSupportCategoryNotEqualTo(String value) {
            addCriterion("SUPPORT_CATEGORY <>", value, "supportCategory");
            return this;
        }

        public Criteria andSupportCategoryGreaterThan(String value) {
            addCriterion("SUPPORT_CATEGORY >", value, "supportCategory");
            return this;
        }

        public Criteria andSupportCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("SUPPORT_CATEGORY >=", value, "supportCategory");
            return this;
        }

        public Criteria andSupportCategoryLessThan(String value) {
            addCriterion("SUPPORT_CATEGORY <", value, "supportCategory");
            return this;
        }

        public Criteria andSupportCategoryLessThanOrEqualTo(String value) {
            addCriterion("SUPPORT_CATEGORY <=", value, "supportCategory");
            return this;
        }

        public Criteria andSupportCategoryLike(String value) {
            addCriterion("SUPPORT_CATEGORY like", value, "supportCategory");
            return this;
        }

        public Criteria andSupportCategoryNotLike(String value) {
            addCriterion("SUPPORT_CATEGORY not like", value, "supportCategory");
            return this;
        }

        public Criteria andSupportCategoryIn(List values) {
            addCriterion("SUPPORT_CATEGORY in", values, "supportCategory");
            return this;
        }

        public Criteria andSupportCategoryNotIn(List values) {
            addCriterion("SUPPORT_CATEGORY not in", values, "supportCategory");
            return this;
        }

        public Criteria andSupportCategoryBetween(String value1, String value2) {
            addCriterion("SUPPORT_CATEGORY between", value1, value2, "supportCategory");
            return this;
        }

        public Criteria andSupportCategoryNotBetween(String value1, String value2) {
            addCriterion("SUPPORT_CATEGORY not between", value1, value2, "supportCategory");
            return this;
        }

        public Criteria andSupportMoneyIsNull() {
            addCriterion("SUPPORT_MONEY is null");
            return this;
        }

        public Criteria andSupportMoneyIsNotNull() {
            addCriterion("SUPPORT_MONEY is not null");
            return this;
        }

        public Criteria andSupportMoneyEqualTo(String value) {
            addCriterion("SUPPORT_MONEY =", value, "supportMoney");
            return this;
        }

        public Criteria andSupportMoneyNotEqualTo(String value) {
            addCriterion("SUPPORT_MONEY <>", value, "supportMoney");
            return this;
        }

        public Criteria andSupportMoneyGreaterThan(String value) {
            addCriterion("SUPPORT_MONEY >", value, "supportMoney");
            return this;
        }

        public Criteria andSupportMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("SUPPORT_MONEY >=", value, "supportMoney");
            return this;
        }

        public Criteria andSupportMoneyLessThan(String value) {
            addCriterion("SUPPORT_MONEY <", value, "supportMoney");
            return this;
        }

        public Criteria andSupportMoneyLessThanOrEqualTo(String value) {
            addCriterion("SUPPORT_MONEY <=", value, "supportMoney");
            return this;
        }

        public Criteria andSupportMoneyLike(String value) {
            addCriterion("SUPPORT_MONEY like", value, "supportMoney");
            return this;
        }

        public Criteria andSupportMoneyNotLike(String value) {
            addCriterion("SUPPORT_MONEY not like", value, "supportMoney");
            return this;
        }

        public Criteria andSupportMoneyIn(List values) {
            addCriterion("SUPPORT_MONEY in", values, "supportMoney");
            return this;
        }

        public Criteria andSupportMoneyNotIn(List values) {
            addCriterion("SUPPORT_MONEY not in", values, "supportMoney");
            return this;
        }

        public Criteria andSupportMoneyBetween(String value1, String value2) {
            addCriterion("SUPPORT_MONEY between", value1, value2, "supportMoney");
            return this;
        }

        public Criteria andSupportMoneyNotBetween(String value1, String value2) {
            addCriterion("SUPPORT_MONEY not between", value1, value2, "supportMoney");
            return this;
        }

        public Criteria andRiskIsNull() {
            addCriterion("RISK is null");
            return this;
        }

        public Criteria andRiskIsNotNull() {
            addCriterion("RISK is not null");
            return this;
        }

        public Criteria andRiskEqualTo(String value) {
            addCriterion("RISK =", value, "risk");
            return this;
        }

        public Criteria andRiskNotEqualTo(String value) {
            addCriterion("RISK <>", value, "risk");
            return this;
        }

        public Criteria andRiskGreaterThan(String value) {
            addCriterion("RISK >", value, "risk");
            return this;
        }

        public Criteria andRiskGreaterThanOrEqualTo(String value) {
            addCriterion("RISK >=", value, "risk");
            return this;
        }

        public Criteria andRiskLessThan(String value) {
            addCriterion("RISK <", value, "risk");
            return this;
        }

        public Criteria andRiskLessThanOrEqualTo(String value) {
            addCriterion("RISK <=", value, "risk");
            return this;
        }

        public Criteria andRiskLike(String value) {
            addCriterion("RISK like", value, "risk");
            return this;
        }

        public Criteria andRiskNotLike(String value) {
            addCriterion("RISK not like", value, "risk");
            return this;
        }

        public Criteria andRiskIn(List values) {
            addCriterion("RISK in", values, "risk");
            return this;
        }

        public Criteria andRiskNotIn(List values) {
            addCriterion("RISK not in", values, "risk");
            return this;
        }

        public Criteria andRiskBetween(String value1, String value2) {
            addCriterion("RISK between", value1, value2, "risk");
            return this;
        }

        public Criteria andRiskNotBetween(String value1, String value2) {
            addCriterion("RISK not between", value1, value2, "risk");
            return this;
        }

        public Criteria andProcessingOpinionIsNull() {
            addCriterion("PROCESSING_OPINION is null");
            return this;
        }

        public Criteria andProcessingOpinionIsNotNull() {
            addCriterion("PROCESSING_OPINION is not null");
            return this;
        }

        public Criteria andProcessingOpinionEqualTo(String value) {
            addCriterion("PROCESSING_OPINION =", value, "processingOpinion");
            return this;
        }

        public Criteria andProcessingOpinionNotEqualTo(String value) {
            addCriterion("PROCESSING_OPINION <>", value, "processingOpinion");
            return this;
        }

        public Criteria andProcessingOpinionGreaterThan(String value) {
            addCriterion("PROCESSING_OPINION >", value, "processingOpinion");
            return this;
        }

        public Criteria andProcessingOpinionGreaterThanOrEqualTo(String value) {
            addCriterion("PROCESSING_OPINION >=", value, "processingOpinion");
            return this;
        }

        public Criteria andProcessingOpinionLessThan(String value) {
            addCriterion("PROCESSING_OPINION <", value, "processingOpinion");
            return this;
        }

        public Criteria andProcessingOpinionLessThanOrEqualTo(String value) {
            addCriterion("PROCESSING_OPINION <=", value, "processingOpinion");
            return this;
        }

        public Criteria andProcessingOpinionLike(String value) {
            addCriterion("PROCESSING_OPINION like", value, "processingOpinion");
            return this;
        }

        public Criteria andProcessingOpinionNotLike(String value) {
            addCriterion("PROCESSING_OPINION not like", value, "processingOpinion");
            return this;
        }

        public Criteria andProcessingOpinionIn(List values) {
            addCriterion("PROCESSING_OPINION in", values, "processingOpinion");
            return this;
        }

        public Criteria andProcessingOpinionNotIn(List values) {
            addCriterion("PROCESSING_OPINION not in", values, "processingOpinion");
            return this;
        }

        public Criteria andProcessingOpinionBetween(String value1, String value2) {
            addCriterion("PROCESSING_OPINION between", value1, value2, "processingOpinion");
            return this;
        }

        public Criteria andProcessingOpinionNotBetween(String value1, String value2) {
            addCriterion("PROCESSING_OPINION not between", value1, value2, "processingOpinion");
            return this;
        }
    }
}